import { Painting, FramingOption, RoomType, Artist } from './types';
import { ART_PAINTINGS } from './artPaintings';
import { assertHiddenIdsResolve, isHidden } from './lib/hiddenArtworks';

export const ARTISTS: Artist[] = [
  {
    id: 'art-01',
    name: 'MESROUR SALAH EDDINE',
    location: 'Casablanca, Morocco',
    bio: 'MESROUR SALAH EDDINE explores the intersection of raw material, digital dreaming, and architectural silence. Working with tactile textures, cybernetic perspectives, and heavy canvas structures, Mesrour creates multidimensional works that evolve under shifting light.',
    philosophy: 'I believe art should bridge the physical and the virtual—existing in space as a living, breathing connection between light, perspective, and organic geometry.',
    avatarUrl: 'https://i.postimg.cc/HW7WS5fh/Man-wearing-futuristic-goggles-f-202607200357-(1).jpg'
  },
  {
    id: 'art-02',
    name: 'NOUREDDIN EL MOBARAKI',
    location: 'Casablanca, Morocco',
    bio: 'A master of light, contrast, and cosmic perspective, Noureddin’s work draws inspiration from fluid geometry and futuristic spaces. His practice combines the natural warmth of Casablanca with virtual, deep-space dimensions.',
    philosophy: 'I seek to capture the infinite depth within a single perspective. By combining 3D projection and vibrant canvas textures, I invite the viewer into an immersive room of reflection.',
    avatarUrl: 'https://i.postimg.cc/MTR9rq1w/Make-me-in-place-2K-202607200557.jpg'
  }
];

/**
 * لوحات الورشة الأصلية (Traditional + Motorbikes + Cars + Gaming).
 * لا تملك حقل image، فتستخدم imageUrl مباشرة.
 * ⛔ ممنوع حذف أي عنصر من هنا: معرّفات pt-xx مرجوع إليها في
 *    HeroSection و PacksView و StickersView.
 */
const STUDIO_PAINTINGS: Painting[] = [
  {
    id: 'pt-02',
    title: 'Sérénité Minérale',
    artistId: 'art-02',
    artistName: 'NOUREDDIN EL MOBARAKI',
    year: 2025,
    style: 'Minimalist',
    sizeCategory: 'Medium',
    widthCm: 80,
    heightCm: 80,
    price: 3360,
    story: 'Sérénité Minérale is a perfect square canvas utilizing deep charcoal fluid acrylics over a textured alabaster plaster background. The continuous hand-drawn black stroke represents structural tranquility and flow. This piece anchors a minimalist space, creating a visual point of stillness and meditation.',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#FAF9F6', '#E2E2E2', '#8E8E8E', '#2A2A2A', '#121212'],
    paletteNames: ['Alabaster White', 'Light Ash', 'Pewter Gray', 'Soot Charcoal', 'Absolute Black'],
    featured: true
  },
  {
    id: 'pt-03',
    title: 'Murmure d’Impasto No. 4',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Textured',
    sizeCategory: 'Large',
    widthCm: 100,
    heightCm: 120,
    price: 4710,
    story: 'Crafted with marble dust plaster, calcium carbonate, and unrefined raw sienna earth pigment, Murmure d’Impasto No. 4 is a tactile masterpiece. Clavel sculpts deep ridges, peaks, and ravines directly onto raw canvas, mimicking geological erosion. The painting is entirely matte, casting elegant natural shadows that dance across the canvas during sunset.',
    imageUrl: 'https://images.unsplash.com/photo-1580136579312-94651dfd596d?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#EAE5DF', '#C5B9AD', '#A18F7D', '#6F5C4B', '#3E3123'],
    paletteNames: ['Chalky Clay', 'Dry Sand', 'Warm Sienna', 'Earth Umber', 'Roasted Cacao'],
    featured: true
  },
  {
    id: 'pt-04',
    title: 'Reflets d’Infini',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2025,
    style: 'Contemporary',
    sizeCategory: 'Collector',
    widthCm: 160,
    heightCm: 120,
    price: 4710,
    story: 'Designed as a collector-scale showpiece, Reflets d’Infini features sweeping washes of deep indigo, lapis lazuli glaze, and iridescent metallic dust. Mesrour layers fluid resin over acrylic washes to achieve a glass-like depth. The painting captures the profound abyss of the Mediterranean Sea at twilight, offering an elegant, dark focus for contemporary dining halls or spacious entranceways.',
    imageUrl: 'https://images.unsplash.com/photo-1549887534-1541e9326642?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#0C1625', '#162C4E', '#325078', '#6F8BAE', '#EAEFF5'],
    paletteNames: ['Midnight Abyss', 'Deep Lapis', 'Prussian Slate', 'Ocean Spray', 'Arctic Ice'],
    featured: false
  },
  {
    id: 'pt-05',
    title: 'Le Poids du Silence',
    artistId: 'art-02',
    artistName: 'NOUREDDIN EL MOBARAKI',
    year: 2026,
    style: 'Minimalist',
    sizeCategory: 'Small',
    widthCm: 60,
    heightCm: 60,
    price: 2150,
    story: 'Part of Noureddin’s famous "Silent Room" collection, this small-scale canvas uses single, intentional layers of high-pigment lamp black over custom off-white gesso. The work explores themes of architectural void and mental pause. Highly recommended to be paired with a clean Raw Oak frame to emphasize its delicate, organic nature.',
    imageUrl: 'https://images.unsplash.com/photo-1502224562085-639556652f33?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#F7F5F0', '#DFDBD3', '#72706D', '#2B2B2A', '#131313'],
    paletteNames: ['Warm Cotton', 'Dry Concrete', 'Muted Charcoal', 'Jet Black', 'Pitch Dark'],
    featured: false
  },
  {
    id: 'pt-06',
    title: 'Éclat Sauvage',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Abstract',
    sizeCategory: 'Large',
    widthCm: 110,
    heightCm: 110,
    price: 4710,
    story: 'Éclat Sauvage brings vibrant structural energy. Created with structured palette knives and raw paint tubes squeezed directly onto linen, this piece features bold impasto gestures of warm ochre, titanium white, and burnt umber. It adds immense character, warmth, and high-fashion focal interest to neutral minimalist walls.',
    imageUrl: 'https://images.unsplash.com/photo-1605721911519-3dfeb3be25e7?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#FDFCF7', '#E5CE93', '#C68735', '#573D21', '#111316'],
    paletteNames: ['Warm Cream', 'Vibrant Ochre', 'Raw Honey', 'Chestnut Oil', 'Obsidian'],
    featured: false
  },
  {
    id: 'pt-07',
    title: 'Brume d’Automne',
    artistId: 'art-02',
    artistName: 'NOUREDDIN EL MOBARAKI',
    year: 2025,
    style: 'Impressionist',
    sizeCategory: 'Medium',
    widthCm: 90,
    heightCm: 70,
    price: 3360,
    story: 'A contemporary take on traditional impressionist landscapes. Noureddin utilizes soft, short brushstrokes and heavy scumbling to build a hazy, atmospheric composition of woodland and wetlands. Soft pastel ochre, misty blue, and pale charcoal blend together seamlessly, capturing the melancholic transitions of the seasonal shift.',
    imageUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#ECECE4', '#D4CEC3', '#C5A987', '#75746C', '#3A3F35'],
    paletteNames: ['Fog Grey', 'Parchment', 'Amber Clay', 'Wet Stone', 'Sage Moss'],
    featured: false
  },
  {
    id: 'pt-08',
    title: 'L’Ombre et le Geste',
    artistId: 'art-02',
    artistName: 'NOUREDDIN EL MOBARAKI',
    year: 2026,
    style: 'Minimalist',
    sizeCategory: 'Collector',
    widthCm: 150,
    heightCm: 150,
    price: 4710,
    story: 'An monumental collector square. Noureddin uses a massive raw Belgian linen canvas as the background, leaving 80% of it completely blank to let the raw flax texture serve as the primary color. A single sweeping charcoal-and-marble-dust gesture cascades from top to bottom, embodying fluid physical strength and absolute minimalism.',
    imageUrl: 'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#E6DEC9', '#CBBDA0', '#8D7F67', '#343332', '#1C1C1B'],
    paletteNames: ['Raw Flax Linen', 'Driftwood Wood', 'Grey Clay', 'Graphite Black', 'Deep Ink'],
    featured: false
  },
  {
    id: 'pt-09',
    title: 'Rêverie Étoilée',
    artistId: 'art-02',
    artistName: 'NOUREDDIN EL MOBARAKI',
    year: 2026,
    style: 'Anime',
    sizeCategory: 'Medium',
    widthCm: 90,
    heightCm: 90,
    price: 3360,
    story: 'Rêverie Étoilée is a limited physical impression blending neoclassical brushwork with Japanese anime aesthetics. Noureddin drafts continuous contours of a solitary figure beneath an expansive, cosmic sunset of soft pastel pinks, deep lavender-violet, and shimmering stars. It acts as an ambient gateway of wonder, bridging contemporary pop culture and heavy canvas weight.',
    imageUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#1F1A3A', '#4A3B6B', '#A58BBA', '#F5C6D6', '#E2D9F3'],
    paletteNames: ['Midnight Lavender', 'Twilight Purple', 'Lilac Sky', 'Cherry Blossom', 'Soft Pastel'],
    featured: true,
    subCategory: 'Jujutsu Kaisen'
  },
  {
    id: 'pt-ani-01',
    title: 'Guts: The Black Swordsman',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Anime',
    sizeCategory: 'Large',
    widthCm: 100,
    heightCm: 120,
    price: 4710,
    story: 'Heavy charcoal impasto and metallic iron pigment capturing the raw, unforgiving stance of Guts under an eclipsed crimson sun.',
    imageUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#121212', '#8B0000', '#2B2B2B', '#E5E5E5', '#4A0000'],
    paletteNames: ['Obsidian Black', 'Eclipse Crimson', 'Iron Gray', 'Steel White', 'Blood Umber'],
    featured: true,
    subCategory: 'Berserk'
  },
  {
    id: 'pt-ani-02',
    title: 'Musashi: Path of the Blade',
    artistId: 'art-02',
    artistName: 'NOUREDDIN EL MOBARAKI',
    year: 2026,
    style: 'Anime',
    sizeCategory: 'Collector',
    widthCm: 130,
    heightCm: 90,
    price: 4710,
    story: 'Traditional sumi-e ink washes combined with gold leaf accents reflecting the inner stillness and martial mastery of Miyamoto Musashi.',
    imageUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#0A0A0A', '#D4AF37', '#F5F5F0', '#3E3E3E', '#8C8C8C'],
    paletteNames: ['Sumi Ink', 'Imperial Gold', 'Parchment', 'Charcoal', 'Slate'],
    featured: true,
    subCategory: 'Vagabond'
  },
  {
    id: 'pt-ani-03',
    title: 'Thorfinn: Shore of Vinland',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Anime',
    sizeCategory: 'Large',
    widthCm: 110,
    heightCm: 80,
    price: 3360,
    story: 'Atmospheric oil glazing depicting Thorfinn looking out over wheat fields under a soft Nordic twilight sky.',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#1E3A8A', '#D97706', '#065F46', '#F3F4F6', '#475569'],
    paletteNames: ['Nordic Sea', 'Wheat Gold', 'Pine Forest', 'Mist White', 'Storm Slate'],
    featured: true,
    subCategory: 'Vinland Saga'
  },
  {
    id: 'pt-ani-04',
    title: 'Sung Jin-Woo: Arise',
    artistId: 'art-02',
    artistName: 'NOUREDDIN EL MOBARAKI',
    year: 2026,
    style: 'Anime',
    sizeCategory: 'Collector',
    widthCm: 140,
    heightCm: 100,
    price: 4710,
    story: 'Electric cyan shadow runes and deep purple aura layers capturing the moment the Shadow Monarch commands his army.',
    imageUrl: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#0F172A', '#00F0FF', '#7E22CE', '#111827', '#F8FAFC'],
    paletteNames: ['Monarch Abyss', 'Neon Cyan', 'Shadow Purple', 'Void Black', 'Aura Light'],
    featured: true,
    subCategory: 'Solo Leveling'
  },
  {
    id: 'pt-ani-05',
    title: 'Goku: Super Saiyan Limitless',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Anime',
    sizeCategory: 'Large',
    widthCm: 120,
    heightCm: 90,
    price: 4710,
    story: 'High-energy impasto strokes in brilliant golden yellow and electric blue aura sparks radiating Saiyan power.',
    imageUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#EAB308', '#2563EB', '#F97316', '#111827', '#FFFFFF'],
    paletteNames: ['Golden Aura', 'Chakra Blue', 'Gi Orange', 'Deep Shadow', 'Flash White'],
    featured: true,
    subCategory: 'Dragon Ball'
  },
  {
    id: 'pt-ani-06',
    title: 'Ippo: Dempsey Roll Motion',
    artistId: 'art-02',
    artistName: 'NOUREDDIN EL MOBARAKI',
    year: 2026,
    style: 'Anime',
    sizeCategory: 'Medium',
    widthCm: 90,
    heightCm: 90,
    price: 3360,
    story: 'Dynamic athletic motion trails and dramatic ring spotlight lighting celebrating Makunouchi Ippo’s iconic signature combination.',
    imageUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#111827', '#DC2626', '#E5E7EB', '#D97706', '#374151'],
    paletteNames: ['Ring Darkness', 'Glove Red', 'Canvas White', 'Leather Bronze', 'Asphalt Shadow'],
    featured: true,
    subCategory: 'Hajime no Ippo'
  },
  {
    id: 'pt-ani-07',
    title: 'Kintaro Oe: Study of Life',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Anime',
    sizeCategory: 'Medium',
    widthCm: 85,
    heightCm: 85,
    price: 3360,
    story: 'Retro 90s anime cel-shading palette and notebook sketch overlay celebrating the humorous, relentless learner Kintaro.',
    imageUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#FACC15', '#0284C7', '#F43F5E', '#111827', '#FFFFFF'],
    paletteNames: ['Golden Yellow', 'Cel Blue', 'Pop Coral', 'Outline Black', 'Paper White'],
    featured: true,
    subCategory: 'Golden Boy'
  },
  {
    id: 'pt-ani-08',
    title: 'Gojo Satoru: Infinite Void',
    artistId: 'art-02',
    artistName: 'NOUREDDIN EL MOBARAKI',
    year: 2026,
    style: 'Anime',
    sizeCategory: 'Collector',
    widthCm: 120,
    heightCm: 120,
    price: 4710,
    story: 'A cosmic expanse of deep navy, glowing cyan eyes, and infinite purple void planes representing Gojo Satoru’s Domain Expansion.',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#030712', '#38BDF8', '#8B5CF6', '#F8FAFC', '#1E1B4B'],
    paletteNames: ['Infinite Void', 'Six Eyes Cyan', 'Curse Violet', 'Starlight White', 'Abyssal Navy'],
    featured: true,
    subCategory: 'Jujutsu Kaisen'
  },
  {
    id: 'pt-ani-09',
    title: 'Naruto & Kurama: Sage Will',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Anime',
    sizeCategory: 'Large',
    widthCm: 110,
    heightCm: 90,
    price: 3360,
    story: 'Swirling fiery orange chakra tails interwoven with serene sage gold lighting, representing harmony with Nine-Tails.',
    imageUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#EA580C', '#EAB308', '#0284C7', '#111827', '#FFFBEB'],
    paletteNames: ['Kurama Fire', 'Sage Gold', 'Rasengan Blue', 'Hokage Black', 'Scroll White'],
    featured: true,
    subCategory: 'Naruto'
  },
  {
    id: 'pt-ani-10',
    title: 'Tanjiro: Hinokami Kagura',
    artistId: 'art-02',
    artistName: 'NOUREDDIN EL MOBARAKI',
    year: 2026,
    style: 'Anime',
    sizeCategory: 'Large',
    widthCm: 100,
    heightCm: 100,
    price: 3360,
    story: 'Ukiyo-e wave contours transforming into roaring Sun Breathing flames around Tanjiro’s black Nichirin katana.',
    imageUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#DC2626', '#059669', '#111827', '#F59E0B', '#FFFFFF'],
    paletteNames: ['Sun Flame Red', 'Haori Green', 'Nichirin Black', 'Ember Gold', 'Blade White'],
    featured: true,
    subCategory: 'Demon Slayer'
  },
  {
    id: 'pt-ani-11',
    title: 'Luffy: Gear 5 Sun God',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Anime',
    sizeCategory: 'Collector',
    widthCm: 130,
    heightCm: 100,
    price: 4710,
    story: 'Surreal white cloud swirls and joyous, roaring freedom energy celebrating Monkey D. Luffy’s awakening as Nika.',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#FFFFFF', '#F59E0B', '#0284C7', '#DC2626', '#111827'],
    paletteNames: ['Nika White', 'Straw Hat Gold', 'Grand Line Ocean', 'Red Line Crimson', 'Conqueror Shadow'],
    featured: true,
    subCategory: 'One Piece'
  },
  {
    id: 'pt-ani-12',
    title: 'Saitama: Serious Series Punch',
    artistId: 'art-02',
    artistName: 'NOUREDDIN EL MOBARAKI',
    year: 2026,
    style: 'Anime',
    sizeCategory: 'Large',
    widthCm: 120,
    heightCm: 80,
    price: 3360,
    story: 'A massive atmospheric shockwave tearing through cloud formations in minimalist yellow, red, and stark white.',
    imageUrl: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#EAB308', '#DC2626', '#FFFFFF', '#111827', '#94A3B8'],
    paletteNames: ['Hero Suit Yellow', 'Glove Red', 'Shockwave White', 'Void Charcoal', 'Atmosphere Slate'],
    featured: true,
    subCategory: 'One Punch Man'
  },
  {
    id: 'pt-ani-13',
    title: 'Asta: Demon Destroyer Grimoire',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Anime',
    sizeCategory: 'Large',
    widthCm: 110,
    heightCm: 90,
    price: 3360,
    story: 'Swirling black anti-magic energy and glowing red demonic wing outlines surrounding Asta’s giant sword.',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#000000', '#991B1B', '#D1D5DB', '#166534', '#FFFFFF'],
    paletteNames: ['Anti-Magic Black', 'Grimoire Crimson', 'Demon Iron', 'Bulls Green', 'Chalk White'],
    featured: true,
    subCategory: 'Black Clover'
  },
  {
    id: 'pt-ani-14',
    title: 'Light & Ryuk: Moonlight Judgment',
    artistId: 'art-02',
    artistName: 'NOUREDDIN EL MOBARAKI',
    year: 2026,
    style: 'Anime',
    sizeCategory: 'Medium',
    widthCm: 90,
    heightCm: 110,
    price: 3360,
    story: 'Gothic chiaroscuro portraiture with stark moonlight silhouettes, apple crimson accents, and Ryuk’s looming shadow.',
    imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#0A0A0A', '#B91C1C', '#E2E8F0', '#4B5563', '#111827'],
    paletteNames: ['Gothic Midnight', 'Apple Red', 'Moonlight Silver', 'Shinigami Gray', 'Notebook Ink'],
    featured: true,
    subCategory: 'Death Note'
  },
  {
    id: 'pt-ani-15',
    title: 'Clare: Silver-Eyed Greatsword',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Anime',
    sizeCategory: 'Large',
    widthCm: 100,
    heightCm: 120,
    price: 4710,
    story: 'Silver armor reflections over a cold, snow-covered mountain canvas, portraying Clare’s serene yet deadly stance.',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#F8FAFC', '#64748B', '#0284C7', '#1E293B', '#E2E8F0'],
    paletteNames: ['Snow White', 'Silver Plate', 'Silver Eye Blue', 'Armor Shadow', 'Cold Steel'],
    featured: true,
    subCategory: 'Claymore'
  },
  {
    id: 'pt-ani-16',
    title: 'Mori Buntarou: Solitary Ridge Ascent',
    artistId: 'art-02',
    artistName: 'NOUREDDIN EL MOBARAKI',
    year: 2026,
    style: 'Anime',
    sizeCategory: 'Large',
    widthCm: 100,
    heightCm: 100,
    price: 3360,
    story: 'Extreme high-altitude mountain ascents, frozen cliff face textures, icy gusts, and the unyielding solitary focus of Mori Buntarou conquering the grand north face solo.',
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#0B1325', '#4A6572', '#E0F2FE', '#94A3B8', '#F8FAFC'],
    paletteNames: ['Abyssal Ridge', 'Glacial Slate', 'Alpine Ice', 'Frost Shadow', 'Summit Snow'],
    featured: true,
    subCategory: 'The Climber'
  },
  {
    id: 'pt-ani-17',
    title: 'Eren: Freedom Beyond the Walls',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Anime',
    sizeCategory: 'Collector',
    widthCm: 150,
    heightCm: 100,
    price: 4710,
    story: 'A monumental canvas of colossal stone walls crumbling into a vast ocean sunset under Eren’s Attack Titan silhouette.',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#78350F', '#0284C7', '#111827', '#D97706', '#F3F4F6'],
    paletteNames: ['Wall Stone', 'Freedom Sea', 'Titan Shadow', 'Sunset Gold', 'Cloud Smoke'],
    featured: true,
    subCategory: 'Attack on Titan'
  },
  {
    id: 'pt-ani-18',
    title: 'Gon & Killua: Aura of Friendship',
    artistId: 'art-02',
    artistName: 'NOUREDDIN EL MOBARAKI',
    year: 2026,
    style: 'Anime',
    sizeCategory: 'Large',
    widthCm: 110,
    heightCm: 90,
    price: 3360,
    story: 'Dual aura currents—Jajanken green and Godspeed lightning blue—intertwining on a dark textured background.',
    imageUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#16A34A', '#38BDF8', '#111827', '#EAB308', '#F8FAFC'],
    paletteNames: ['Jajanken Green', 'Godspeed Cyan', 'Void Darkness', 'Hunter Gold', 'Aura Spark'],
    featured: true,
    subCategory: 'Hunter x Hunter'
  },
  {
    id: 'pt-10',
    title: 'Sanctuaire Perdu',
    artistId: 'art-02',
    artistName: 'NOUREDDIN EL MOBARAKI',
    year: 2026,
    style: 'Gaming',
    sizeCategory: 'Large',
    widthCm: 110,
    heightCm: 90,
    price: 3360,
    story: 'Sanctuaire Perdu is an abstract monumental landscape inspired by legendary fantasy adventure games. It features a glowing, mystical doorway set within monolithic stone arches and ancient ruins. Noureddin uses neon fluid pigments and physical relief pastes to evoke a rich, high-contrast digital glow, bringing the immersive interactive universe of virtual quests into physical reality.',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#0A192F', '#172A45', '#306F8A', '#00F0FF', '#00FF87'],
    paletteNames: ['Abyssal Navy', 'Deep Teal', 'Cyan Flare', 'Neon Matrix', 'Vibrant Jade'],
    featured: true,
    subCategory: 'PRISM Studio'
  },
  {
    id: 'pt-11',
    title: 'Cinéma Noir No. 7',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Films',
    sizeCategory: 'Large',
    widthCm: 120,
    heightCm: 80,
    price: 3360,
    story: 'Cinéma Noir No. 7 pays homage to classical mid-century French New Wave and cinematic film noir suspense. Clavel models structured, dramatic backlights using deep carbon blacks, interspersed with bright crimson paint drips that mimic the glow of vintage neon theaters in the rain. It is an exquisite study of shadow, suspense, and raw atmosphere.',
    imageUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#0F0F0F', '#242424', '#D21F3C', '#E2A414', '#EDEDED'],
    paletteNames: ['Matte Obsidian', 'Soot Charcoal', 'Cinematic Scarlet', 'Golden Marquee', 'Silver Screen'],
    featured: true,
    subCategory: 'Se7en'
  },
  {
    id: 'pt-flm-01',
    title: 'Se7en: Rain of Sins',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Films',
    sizeCategory: 'Large',
    widthCm: 110,
    heightCm: 90,
    price: 3360,
    story: 'Dark rain-slicked urban alleyways and stark flashlight beams illuminating the heavy shadows of David Fincher crime masterpiece.',
    imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#0A0A0A', '#4A0000', '#2B2B2B', '#D4AF37', '#8C8C8C'],
    paletteNames: ['Rain Charcoal', 'Sin Crimson', 'Noir Shadow', 'Flashlight Gold', 'Wet Asphalt'],
    featured: true,
    subCategory: 'Se7en'
  },
  {
    id: 'pt-flm-02',
    title: 'Fight Club: Chemical Burn',
    artistId: 'art-02',
    artistName: 'NOUREDDIN EL MOBARAKI',
    year: 2026,
    style: 'Films',
    sizeCategory: 'Collector',
    widthCm: 130,
    heightCm: 90,
    price: 4710,
    story: 'Surreal neon pink paper soap contrast, basement shadow boxers, and crumbling urban skyline silhouettes.',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#EC4899', '#111827', '#374151', '#F59E0B', '#F8FAFC'],
    paletteNames: ['Soap Pink', 'Basement Black', 'Concrete Gray', 'Sodium Gold', 'Neon White'],
    featured: true,
    subCategory: 'Fight Club'
  },
  {
    id: 'pt-flm-03',
    title: 'Memento: Fragmented Memory',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Films',
    sizeCategory: 'Medium',
    widthCm: 90,
    heightCm: 90,
    price: 3360,
    story: 'Layered polaroid contours and sepia handwriting washes capturing the non-linear psychological puzzle.',
    imageUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#78350F', '#FEF3C7', '#1F2937', '#D97706', '#F3F4F6'],
    paletteNames: ['Sepia Ink', 'Polaroid Cream', 'Tattoo Black', 'Amber Flash', 'Memory Slate'],
    featured: true,
    subCategory: 'Memento'
  },
  {
    id: 'pt-flm-05',
    title: 'Peaky Blinders: By Order of the Shelby',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Films',
    sizeCategory: 'Collector',
    widthCm: 140,
    heightCm: 90,
    price: 4710,
    story: 'Atmospheric 1920s Birmingham foundry smoke, sharp razor-edged flat cap silhouettes, and golden whiskey tones.',
    imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#0F172A', '#D97706', '#4B5563', '#B45309', '#F1F5F9'],
    paletteNames: ['Garrison Charcoal', 'Whiskey Amber', 'Cap Wool', 'Foundry Fire', 'Smoke White'],
    featured: true,
    subCategory: 'Peaky Blinders'
  },
  {
    id: 'pt-flm-06',
    title: 'Breaking Bad: Blue Sky Empire',
    artistId: 'art-02',
    artistName: 'NOUREDDIN EL MOBARAKI',
    year: 2026,
    style: 'Films',
    sizeCategory: 'Large',
    widthCm: 120,
    heightCm: 80,
    price: 3360,
    story: 'Sunbaked New Mexico desert horizon with yellow hazmat suits and brilliant crystal blue glare.',
    imageUrl: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#EAB308', '#00F0FF', '#78350F', '#111827', '#FFFFFF'],
    paletteNames: ['Hazmat Yellow', 'Blue Sky Cyan', 'Desert Sienna', 'Heisenberg Black', 'Chemical White'],
    featured: true,
    subCategory: 'Breaking Bad'
  },
  {
    id: 'pt-flm-07',
    title: 'Game of Thrones: Winter & Fire',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Films',
    sizeCategory: 'Collector',
    widthCm: 150,
    heightCm: 100,
    price: 4710,
    story: 'Forged iron sword hilts of the Great Throne beneath dragon flame embers and frosty northern twilight.',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#1E293B', '#DC2626', '#94A3B8', '#D97706', '#F8FAFC'],
    paletteNames: ['Winterfell Steel', 'Dragon Flame', 'Iron Throne', 'Valyrian Gold', 'Frost White'],
    featured: true,
    subCategory: 'Game of Thrones'
  },
  {
    id: 'pt-flm-08',
    title: 'Better Call Saul: Justice in Neon',
    artistId: 'art-02',
    artistName: 'NOUREDDIN EL MOBARAKI',
    year: 2026,
    style: 'Films',
    sizeCategory: 'Medium',
    widthCm: 90,
    heightCm: 90,
    price: 3360,
    story: 'Rich Albuquerque neon lighting, vibrant colorful suits, and the golden scales of justice.',
    imageUrl: 'https://images.unsplash.com/photo-1580136579312-94651dfd596d?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#EAB308', '#2563EB', '#D97706', '#111827', '#F3F4F6'],
    paletteNames: ['Saul Yellow', 'Courtroom Blue', 'Lawyer Gold', 'Office Shadow', 'Cinnabon Cream'],
    featured: true,
    subCategory: 'Better Call Saul'
  },
  {
    id: 'pt-flm-09',
    title: 'The Sopranos: Jersey Family',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Films',
    sizeCategory: 'Large',
    widthCm: 110,
    heightCm: 90,
    price: 3360,
    story: 'Dark mahogany executive booths, rich cigar smoke drifts, and North Jersey mob hierarchy chiaroscuro.',
    imageUrl: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#111827', '#78350F', '#B91C1C', '#D97706', '#E5E7EB'],
    paletteNames: ['Bada Bing Black', 'Mahogany Wood', 'Cigar Crimson', 'Diner Amber', 'Silk Shirt White'],
    featured: true,
    subCategory: 'The Sopranos'
  },
  {
    id: 'pt-flm-10',
    title: 'Six Feet Under: Eternal Departure',
    artistId: 'art-02',
    artistName: 'NOUREDDIN EL MOBARAKI',
    year: 2026,
    style: 'Films',
    sizeCategory: 'Medium',
    widthCm: 90,
    heightCm: 110,
    price: 3360,
    story: 'Serene white floral arrangements, soft mortality shadows, and deeply philosophical undertones.',
    imageUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#FFFFFF', '#166534', '#111827', '#6B7280', '#FEF3C7'],
    paletteNames: ['Linen White', 'Funeral Cypress', 'Mortuary Shadow', 'Grief Slate', 'Memorial Gold'],
    featured: true,
    subCategory: 'Six Feet Under'
  },
  {
    id: 'pt-flm-11',
    title: 'From: The Talisman Town',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Films',
    sizeCategory: 'Large',
    widthCm: 100,
    heightCm: 100,
    price: 3360,
    story: 'Eerie nocturnal forest canopy with carved stone talismans glowing against the ominous night.',
    imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#052E16', '#111827', '#D97706', '#DC2626', '#E5E7EB'],
    paletteNames: ['Forest Night', 'Monsters Void', 'Talisman Gold', 'Blood Seal', 'Fog White'],
    featured: true,
    subCategory: 'From'
  },
  {
    id: 'pt-flm-12',
    title: 'Dark: Winden Time Loop',
    artistId: 'art-02',
    artistName: 'NOUREDDIN EL MOBARAKI',
    year: 2026,
    style: 'Films',
    sizeCategory: 'Collector',
    widthCm: 130,
    heightCm: 90,
    price: 4710,
    story: 'Rain-drenched yellow raincoat silhouette standing before the cavern vortex and triquetra time portals.',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#EAB308', '#0F172A', '#3B82F6', '#1E293B', '#F8FAFC'],
    paletteNames: ['Raincoat Yellow', 'Winden Cave', 'Vortex Blue', 'Nuclear Slate', 'Loop Mist'],
    featured: true,
    subCategory: 'Dark'
  },
  {
    id: 'pt-flm-13',
    title: 'Lost: The Mysterious Island',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Films',
    sizeCategory: 'Large',
    widthCm: 120,
    heightCm: 80,
    price: 3360,
    story: 'Emerald rainforest canopy, sunlit ocean surf, and the metallic hatch door buried in the sand.',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#047857', '#0284C7', '#111827', '#F59E0B', '#FFFFFF'],
    paletteNames: ['Jungle Emerald', 'Ocean Turquoise', 'Smoke Monster', 'Island Sun', 'Hatch Steel'],
    featured: true,
    subCategory: 'Lost'
  },
  {
    id: 'pt-flm-14',
    title: 'The Last Kingdom: Destiny Is All',
    artistId: 'art-02',
    artistName: 'NOUREDDIN EL MOBARAKI',
    year: 2026,
    style: 'Films',
    sizeCategory: 'Large',
    widthCm: 110,
    heightCm: 90,
    price: 3360,
    story: 'Anglo-Saxon shield wall battlelines, fiery torches, and Uhtreds silver sword amber highlights.',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#451A03', '#1E293B', '#EA580C', '#94A3B8', '#F3F4F6'],
    paletteNames: ['Saxon Mud', 'Armor Slate', 'Battle Fire', 'Uhtred Silver', 'Banner White'],
    featured: true,
    subCategory: 'The Last Kingdom'
  },
  {
    id: 'pt-flm-15',
    title: 'The Walking Dead: Atlanta Highway',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Films',
    sizeCategory: 'Large',
    widthCm: 120,
    heightCm: 80,
    price: 3360,
    story: 'Atmospheric desolate highway stretch, weathered sheriffs badge brass, and rustic survival aesthetics.',
    imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#78350F', '#4B5563', '#111827', '#D97706', '#E5E7EB'],
    paletteNames: ['Rust Dirt', 'Decay Gray', 'Walker Shadow', 'Badge Brass', 'Asphalt Dust'],
    featured: true,
    subCategory: 'The Walking Dead'
  },
  {
    id: 'pt-flm-16',
    title: 'The Wire: West Baltimore',
    artistId: 'art-02',
    artistName: 'NOUREDDIN EL MOBARAKI',
    year: 2026,
    style: 'Films',
    sizeCategory: 'Medium',
    widthCm: 90,
    heightCm: 90,
    price: 3360,
    story: 'Gritty Baltimore brick textures, police wiretape audio waveforms, and raw urban realism.',
    imageUrl: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#991B1B', '#1F2937', '#475569', '#D97706', '#F8FAFC'],
    paletteNames: ['Brick Red', 'Street Black', 'Wiretape Gray', 'Sodium Light', 'Paper White'],
    featured: true,
    subCategory: 'The Wire'
  },
  {
    id: 'pt-flm-17',
    title: 'Joker: Stairway Dance',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Films',
    sizeCategory: 'Collector',
    widthCm: 120,
    heightCm: 100,
    price: 4710,
    story: 'Vibrant yellow and burgundy suit tones, staircase dance shadows, and Gotham 1970s gritty atmosphere.',
    imageUrl: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#991B1B', '#EAB308', '#065F46', '#111827', '#FFFFFF'],
    paletteNames: ['Burgundy Suit', 'Joker Yellow', 'Makeup Green', 'Gotham Shadow', 'Clown White'],
    featured: true,
    subCategory: 'Joker'
  },
  {
    id: 'pt-flm-18',
    title: 'The Boys: Compound V Overdrive',
    artistId: 'art-02',
    artistName: 'NOUREDDIN EL MOBARAKI',
    year: 2026,
    style: 'Films',
    sizeCategory: 'Large',
    widthCm: 110,
    heightCm: 90,
    price: 3360,
    story: 'Electric blue Compound V liquid glows, fiery laser eyes, and rebellious anti-hero pop art strokes.',
    imageUrl: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#00F0FF', '#DC2626', '#111827', '#F59E0B', '#F8FAFC'],
    paletteNames: ['Compound V Cyan', 'Laser Red', 'Vought Void', 'Homelander Gold', 'Pop White'],
    featured: true,
    subCategory: 'The Boys'
  },
  {
    id: 'pt-flm-19',
    title: 'The Dark Knight: Watchful Protector',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Films',
    sizeCategory: 'Collector',
    widthCm: 140,
    heightCm: 90,
    price: 4710,
    story: 'Bat-signal beam cutting through rainy Gotham skyscraper clouds with chaotic Joker card red accents.',
    imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#030712', '#38BDF8', '#B91C1C', '#1E293B', '#F8FAFC'],
    paletteNames: ['Bat Cave Black', 'Signal Cyan', 'Joker Card Crimson', 'Gothic Slate', 'Skyline Flash'],
    featured: true,
    subCategory: 'The Dark Knight'
  },
  {
    id: 'pt-flm-20',
    title: 'La Casa de Papel: Resistance Bella Ciao',
    artistId: 'art-02',
    artistName: 'NOUREDDIN EL MOBARAKI',
    year: 2026,
    style: 'Films',
    sizeCategory: 'Large',
    widthCm: 100,
    heightCm: 100,
    price: 3360,
    story: 'Iconic Salvador Dalí mask in bold red jumpsuit hues with gold mint bullion reflections.',
    imageUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#DC2626', '#D97706', '#111827', '#F3F4F6', '#991B1B'],
    paletteNames: ['Jumpsuit Red', 'Mint Gold', 'Mask Shadow', 'Bella White', 'Professor Crimson'],
    featured: true,
    subCategory: 'La Casa de Papel'
  },
  {
    id: 'pt-flm-21',
    title: '2001: Monolith & Stargate',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Films',
    sizeCategory: 'Collector',
    widthCm: 130,
    heightCm: 100,
    price: 4710,
    story: 'Luminous HAL 9000 eye flare, stark white Discovery One corridors, and monolithic black stone alignment.',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#000000', '#EF4444', '#FFFFFF', '#3B82F6', '#6B7280'],
    paletteNames: ['Monolith Black', 'HAL Red Eye', 'Corridor White', 'Stargate Blue', 'Lunar Dust'],
    featured: true,
    subCategory: '2001: A Space Odyssey'
  },
  {
    id: 'pt-flm-22',
    title: 'Oppenheimer: Trinity Fireball',
    artistId: 'art-02',
    artistName: 'NOUREDDIN EL MOBARAKI',
    year: 2026,
    style: 'Films',
    sizeCategory: 'Collector',
    widthCm: 140,
    heightCm: 90,
    price: 4710,
    story: 'High-impact atomic fire swirl in desert dawn, overlaid with black-and-white quantum physics equations.',
    imageUrl: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#F97316', '#EAB308', '#000000', '#FFFFFF', '#4B5563'],
    paletteNames: ['Trinity Fire', 'Fission Gold', 'Quantum Black', 'Chalk White', 'Los Alamos Slate'],
    featured: true,
    subCategory: 'Oppenheimer'
  },
  {
    id: 'pt-flm-23',
    title: 'Interstellar: Gargantua Singularity',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Films',
    sizeCategory: 'Collector',
    widthCm: 150,
    heightCm: 100,
    price: 4710,
    story: 'Massive glowing accretion disk of Gargantua bending light over the infinite cosmic abyss.',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#F59E0B', '#0F172A', '#38BDF8', '#FFFFFF', '#78350F'],
    paletteNames: ['Accretion Gold', 'Cosmic Abyss', 'Wormhole Blue', 'Starlight White', 'Cornfield Sienna'],
    featured: true,
    subCategory: 'Interstellar'
  },
  {
    id: 'pt-flm-24',
    title: 'City of God: Favela Sunburst',
    artistId: 'art-02',
    artistName: 'NOUREDDIN EL MOBARAKI',
    year: 2026,
    style: 'Films',
    sizeCategory: 'Large',
    widthCm: 110,
    heightCm: 90,
    price: 3360,
    story: 'Sun-drenched Rio de Janeiro favela rooftops captured in warm 1970s vintage orange and golden grain.',
    imageUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#EA580C', '#D97706', '#0284C7', '#111827', '#FEF3C7'],
    paletteNames: ['Favela Orange', 'Rio Sun Gold', 'Ocean Sky', 'Shadow Black', 'Vintage Grain'],
    featured: true,
    subCategory: 'City of God'
  },
  {
    id: 'pt-flm-25',
    title: 'Paul: Area 51 Highway',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Films',
    sizeCategory: 'Medium',
    widthCm: 90,
    heightCm: 90,
    price: 3360,
    story: 'Desert RV roadtrip under neon green extraterrestrial night skies and starlight horizon.',
    imageUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#22C55E', '#1E1B4B', '#F59E0B', '#F8FAFC', '#334155'],
    paletteNames: ['Alien Green', 'Area 51 Night', 'Desert Dusk', 'Starlight White', 'RV Shadow'],
    featured: true,
    subCategory: 'Paul'
  },
  {
    id: 'pt-flm-26',
    title: 'Captain Phillips: Ocean Rescue',
    artistId: 'art-02',
    artistName: 'NOUREDDIN EL MOBARAKI',
    year: 2026,
    style: 'Films',
    sizeCategory: 'Large',
    widthCm: 120,
    heightCm: 80,
    price: 3360,
    story: 'Deep navy maritime waves, industrial container ship iron, and intense high-seas rescue drama.',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#0F172A', '#0284C7', '#DC2626', '#64748B', '#F8FAFC'],
    paletteNames: ['Ocean Navy', 'Maritime Blue', 'Rescue Flare Red', 'Ship Iron', 'Wave Foam White'],
    featured: true,
    subCategory: 'Captain Phillips'
  },
  {
    id: 'pt-14',
    title: 'Nostalgie Rétro',
    artistId: 'art-02',
    artistName: 'NOUREDDIN EL MOBARAKI',
    year: 2026,
    style: 'Cars',
    sizeCategory: 'Large',
    widthCm: 120,
    heightCm: 90,
    price: 4710,
    story: 'Nostalgie Rétro is a stunning study of the timeless 911 silhouette, rendered in precise, flowing minimalist ink lines over an atmospheric sage green plaster wash. It explores the fluid aerodynamic geometry that turns automotive design into fine art. Noureddin balances precision with rich painterly textures.',
    imageUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#2A2A2A', '#A18F7D', '#EDEDED', '#162C4E', '#C68735'],
    paletteNames: ['Guards Black', 'Sage Wash', 'Polished Silver', 'Midnight Blue', 'Amber Lens'],
    featured: true,
    subCategory: 'Technical Specifications'
  },
  {
    id: 'pt-15',
    title: 'Neon Horizon',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Cars',
    sizeCategory: 'Medium',
    widthCm: 85,
    heightCm: 65,
    price: 3360,
    story: 'Neon Horizon represents the sleek aerodynamic shape of a futuristic supercar traversing a coastal highway at twilight. Mesrour overlays deep Prussian Blue acrylic washes with high-relief electric cyan and neon green stripes. The result is a piece that vibrates with mechanical rhythm and light trails.',
    imageUrl: 'https://images.unsplash.com/photo-1525609004556-c46c7d6cf0a3?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#162C4E', '#0A192F', '#00F0FF', '#00FF87', '#EDEDED'],
    paletteNames: ['Prussian Blue', 'Abyssal Night', 'Cyan Beam', 'Laser Green', 'White Hot Chrome'],
    featured: false,
    subCategory: 'Track & Performance'
  },
  {
    id: 'pt-16',
    title: 'Yamaha XSR 900',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Motorbikes',
    sizeCategory: 'Large',
    widthCm: 100,
    heightCm: 75,
    price: 3360,
    story: 'A magnificent tribute to Japanese engineering and heritage racing aesthetic. This painting highlights the neo-retro architecture of the Yamaha XSR 900 with rich cobalt and speed-block blue oil washes, accented by shimmering gold leaf on the front forks and raw carbon brushstrokes around the exhaust pipes.',
    imageUrl: 'https://noureddinelmobaraki-web.github.io/nl-audio-cdn/Sportbike%20(2)/3.webp',
    colorPalette: ['#005691', '#D4AF37', '#121212', '#EDEDED', '#8C7A6B'],
    paletteNames: ['Heritage Blue', 'Anodized Gold', 'Exhaust Carbon', 'Polished Steel', 'Engine Bronze'],
    featured: true,
    subCategory: 'YAMAHA'
  },
  {
    id: 'pt-17',
    title: 'BMW S1000RR M-Performance',
    artistId: 'art-02',
    artistName: 'NOUREDDIN EL MOBARAKI',
    year: 2026,
    style: 'Motorbikes',
    sizeCategory: 'Large',
    widthCm: 100,
    heightCm: 100,
    price: 3360,
    story: 'A stunning architectural showcase of the BMW S1000RR in premium M-Performance colors. Noureddin layers textured asphalt brushstrokes and neon white highlights to represent track precision and raw speed.',
    imageUrl: 'https://noureddinelmobaraki-web.github.io/nl-audio-cdn/Sportbike%20(2)/6.webp',
    colorPalette: ['#1E3A8A', '#EF4444', '#FFFFFF', '#121212', '#94A3B8'],
    paletteNames: ['Motorsport Blue', 'Racing Red', 'Alpine White', 'Carbon Fiber', 'Slate Gray'],
    featured: true,
    subCategory: 'BMW'
  },
  {
    id: 'pt-18',
    title: 'Ducati Panigale V4 S',
    artistId: 'art-02',
    artistName: 'NOUREDDIN EL MOBARAKI',
    year: 2026,
    style: 'Motorbikes',
    sizeCategory: 'Large',
    widthCm: 100,
    heightCm: 100,
    price: 3360,
    story: 'The ultimate expression of Italian speed and aerodynamic sculpture. A beautiful high-contrast render of the Panigale V4 S, capturing the iconic red fairings and aggressive carbon winglets with metallic copper tones.',
    imageUrl: 'https://noureddinelmobaraki-web.github.io/nl-audio-cdn/Sportbike%20(2)/4.webp',
    colorPalette: ['#B91C1C', '#121212', '#F3F4F6', '#D97706', '#374151'],
    paletteNames: ['Rosso Red', 'Carbon Black', 'Titanium Silver', 'Anodized Gold', 'Anthracite'],
    featured: true,
    subCategory: 'DUCATI'
  },
  {
    id: 'pt-19',
    title: 'Kawasaki Z1000 Stealth Black',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Motorbikes',
    sizeCategory: 'Large',
    widthCm: 100,
    heightCm: 100,
    price: 3360,
    story: 'The Sugomi design of the Kawasaki Z1000 rendered in complete matte black and deep forest green accents. A dark, moody tribute to aggressive streetfighter engineering and nighttime velocity.',
    imageUrl: 'https://noureddinelmobaraki-web.github.io/nl-audio-cdn/Sportbike%20(2)/1.webp',
    colorPalette: ['#111827', '#15803D', '#4B5563', '#9CA3AF', '#374151'],
    paletteNames: ['Stealth Black', 'Kawasaki Green', 'Dark Graphite', 'Polished Silver', 'Shadow Gray'],
    featured: true,
    subCategory: 'KAWASAKI'
  },
  {
    id: 'pt-20',
    title: 'Kawasaki Z1000 Bumblebee Yellow',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Motorbikes',
    sizeCategory: 'Large',
    widthCm: 100,
    heightCm: 100,
    price: 3360,
    story: 'An electric, transformers-inspired rendering of the Kawasaki Z1000 superbike specs in a striking Bumblebee Yellow colorway. It brings the raw energy of high-octane mechanical streetfighters to life.',
    imageUrl: 'https://i.postimg.cc/6Qw9fcRF/Kawasaki-Z1000-Superbike-Specs-Aesthetic-Transformers-Bumblebee-Yellow-follow-alizeyyykhan.jpg',
    colorPalette: ['#EAB308', '#111827', '#4B5563', '#FFFFFF', '#D97706'],
    paletteNames: ['Bumblebee Yellow', 'Chassis Black', 'Slate Gray', 'Pure White', 'Amber Gold'],
    featured: true,
    subCategory: 'KAWASAKI'
  },
  {
    id: 'pt-21',
    title: 'KTM Duke 390',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Motorbikes',
    sizeCategory: 'Medium',
    widthCm: 90,
    heightCm: 90,
    price: 3360,
    story: 'The lightweight corner rocket captured in its signature sharp orange trellis frame. This design celebrates the aggressive, agile posture of the Duke 390 with geometric high-contrast splash marks and asphalt grays.',
    imageUrl: 'https://noureddinelmobaraki-web.github.io/nl-audio-cdn/Sportbike%20(2)/7.webp',
    colorPalette: ['#F97316', '#111827', '#FFFFFF', '#6B7280', '#D1D5DB'],
    paletteNames: ['KTM Orange', 'Trellis Black', 'Bright White', 'Subframe Gray', 'Aluminium'],
    featured: true,
    subCategory: 'KTM'
  },
  {
    id: 'pt-22',
    title: 'Superbike Specifications',
    artistId: 'art-02',
    artistName: 'NOUREDDIN EL MOBARAKI',
    year: 2026,
    style: 'Motorbikes',
    sizeCategory: 'Large',
    widthCm: 100,
    heightCm: 100,
    price: 3360,
    story: 'A deep technical blue-print poster celebrating the racing specifications, horsepower, and aerodynamic dimensions of modern GP superbikes. It blends technical mechanical sketches with beautiful painterly oil glazes.',
    imageUrl: 'https://i.postimg.cc/SKqyfd8P/Super-bike.jpg',
    colorPalette: ['#0284C7', '#111827', '#F8FAFC', '#64748B', '#0F172A'],
    paletteNames: ['Blueprint Blue', 'Soot Charcoal', 'Blueprint White', 'Technical Gray', 'Abyssal Black'],
    featured: true,
    subCategory: 'BMW'
  },
  {
    id: 'pt-23',
    title: 'Suzuki Hayabusa GSX1300R',
    artistId: 'art-02',
    artistName: 'NOUREDDIN EL MOBARAKI',
    year: 2026,
    style: 'Motorbikes',
    sizeCategory: 'Collector',
    widthCm: 120,
    heightCm: 120,
    price: 4710,
    story: 'The ultimate speed legend—the Suzuki Hayabusa. This painting honors the sweeping aerodynamic lines and legendary speed record-breaking heritage with rich indigo, copper metallic, and deep carbon highlights.',
    imageUrl: 'https://noureddinelmobaraki-web.github.io/nl-audio-cdn/Sportbike%20(2)/5.webp',
    colorPalette: ['#312E81', '#111827', '#D97706', '#E2E8F0', '#4B5563'],
    paletteNames: ['Indigo Pearl', 'Chassis Black', 'Bronze Accent', 'Silver Fairing', 'Graphite'],
    featured: true,
    subCategory: 'Suzuki'
  },
  {
    id: 'pt-mb-01',
    title: 'Harley-Davidson Fat Boy Custom',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Motorbikes',
    sizeCategory: 'Large',
    widthCm: 120,
    heightCm: 80,
    price: 3360,
    story: 'Low-slung chrome stance, massive V-twin motor, polished aluminium disc wheels, and deep leather textures celebrating American cruiser heritage.',
    imageUrl: 'https://noureddinelmobaraki-web.github.io/nl-audio-cdn/Sportbike%20(2)/8.webp',
    colorPalette: ['#111827', '#D4AF37', '#E5E7EB', '#78350F', '#374151'],
    paletteNames: ['Chrome Silver', 'Engine Gold', 'Parchment White', 'Saddle Leather', 'Chassis Charcoal'],
    featured: true,
    subCategory: 'Harley-Davidson'
  },
  {
    id: 'pt-mb-04',
    title: 'Royal Enfield Continental GT 650',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Motorbikes',
    sizeCategory: 'Large',
    widthCm: 100,
    heightCm: 80,
    price: 3360,
    story: 'Pure cafe racer heritage featuring twin cylinder 650cc motor, clip-on handlebars, sculpted fuel tank, and timeless British-Indian racing aesthetics.',
    imageUrl: 'https://noureddinelmobaraki-web.github.io/nl-audio-cdn/royal.webp',
    colorPalette: ['#111827', '#DC2626', '#E5E7EB', '#D4AF37', '#374151'],
    paletteNames: ['Chrome Finish', 'British Racing Red', 'Brushed Aluminum', 'Gold Accents', 'Saddle Black'],
    featured: true,
    subCategory: 'Royal enfield'
  },
  {
    id: 'pt-mb-02',
    title: 'BMW R1250 GS Adventure',
    artistId: 'art-02',
    artistName: 'NOUREDDIN EL MOBARAKI',
    year: 2026,
    style: 'Motorbikes',
    sizeCategory: 'Large',
    widthCm: 110,
    heightCm: 90,
    price: 3360,
    story: 'Rugged dual-sport endurance chassis, mud-splattered spoked wheels, and high alpine mountain trail perspectives built for world-crossing journeys.',
    imageUrl: 'https://noureddinelmobaraki-web.github.io/nl-audio-cdn/Sportbike/4.webp',
    colorPalette: ['#1E3A8A', '#DC2626', '#F8FAFC', '#4B5563', '#111827'],
    paletteNames: ['Rallye Blue', 'Motorsport Red', 'Summit White', 'Trail Dust Slate', 'Engine Shadow'],
    featured: true,
    subCategory: 'BMW'
  },
  {
    id: 'pt-mb-03',
    title: 'Yamaha TMAX 560 Tech MAX',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Motorbikes',
    sizeCategory: 'Medium',
    widthCm: 95,
    heightCm: 70,
    price: 3360,
    story: 'Aggressive maxi-scooter aerodynamics, dual LED projector eyes, and polished urban commuting posture in liquid dark metal gray.',
    imageUrl: 'https://noureddinelmobaraki-web.github.io/nl-audio-cdn/Sportbike/6.webp',
    colorPalette: ['#1F2937', '#0284C7', '#9CA3AF', '#000000', '#F3F4F6'],
    paletteNames: ['Liquid Dark Gray', 'Tech Blue', 'Forged Silver', 'Matte Void', 'Neon White'],
    featured: true,
    subCategory: 'YAMAHA'
  },
  {
    id: 'pt-mb-05',
    title: 'Honda CBR1000RR-R Fireblade SP',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Motorbikes',
    sizeCategory: 'Large',
    widthCm: 100,
    heightCm: 80,
    price: 3360,
    story: 'Pure MotoGP technology brought to the road. The Fireblade SP features Grand Prix aerodynamic winglets, iconic Tricour colorway, titanium Akrapovic exhaust, and aggressive track stance.',
    imageUrl: 'https://noureddinelmobaraki-web.github.io/nl-audio-cdn/Sportbike%20(2)/2.webp',
    colorPalette: ['#DC2626', '#2563EB', '#FFFFFF', '#111827', '#E5E7EB'],
    paletteNames: ['Grand Prix Red', 'HRC Blue', 'Pearl White', 'Titanium Black', 'Brushed Metal'],
    featured: true,
    subCategory: 'honda'
  },
  {
    id: 'pt-24',
    title: 'Porsche 911 Blueprint Spec',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Cars',
    sizeCategory: 'Collector',
    widthCm: 150,
    heightCm: 100,
    price: 4710,
    story: 'A sophisticated technical layout displaying the precise engineering specs, dimensions, chassis layout, and flat-six engine configuration of the 911 GT3 RS. Rendered in clean monochrome chalk on blueprint slate.',
    imageUrl: 'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#0F172A', '#38BDF8', '#F1F5F9', '#94A3B8', '#0284C7'],
    paletteNames: ['Blueprint Slate', 'Chalk Cyan', 'Ice White', 'Steel Gray', 'Ocean Cobalt'],
    featured: true,
    subCategory: 'Technical Specifications'
  },
  {
    id: 'pt-25',
    title: 'Ferrari F40 Aerodynamics',
    artistId: 'art-02',
    artistName: 'NOUREDDIN EL MOBARAKI',
    year: 2026,
    style: 'Cars',
    sizeCategory: 'Large',
    widthCm: 120,
    heightCm: 100,
    price: 4710,
    story: 'A gorgeous engineering schematic capturing the iconic drag coefficient, wedge silhouette, and carbon fiber cooling vents of the historic Ferrari F40. The background fuses carbon mesh texture with racing red oil layers.',
    imageUrl: 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#DC2626', '#111827', '#FBBF24', '#F3F4F6', '#1F2937'],
    paletteNames: ['Corsa Red', 'Carbon Black', 'Modena Yellow', 'Titanium White', 'Engine Anthracite'],
    featured: true
  },
  {
    id: 'pt-car-01',
    title: 'Mercedes-AMG GT Black Series',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Cars',
    sizeCategory: 'Large',
    widthCm: 120,
    heightCm: 90,
    price: 4710,
    story: 'High-relief carbon aerodynamics and aggressive Panamericana grille stance. The Mercedes-AMG GT Black Series in emerald green metallic wash and matte carbon accents.',
    imageUrl: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#065F46', '#111827', '#E5E7EB', '#047857', '#374151'],
    paletteNames: ['AMG Green', 'Carbon Obsidian', 'Chrome Accent', 'Emerald Metallic', 'Chassis Slate'],
    featured: true,
    subCategory: 'mercedes'
  },
  {
    id: 'pt-car-02',
    title: 'BMW M4 Competition Spec',
    artistId: 'art-02',
    artistName: 'NOUREDDIN EL MOBARAKI',
    year: 2026,
    style: 'Cars',
    sizeCategory: 'Large',
    widthCm: 120,
    heightCm: 80,
    price: 4710,
    story: 'Aggressive M-TwinPower turbo stance featuring iconic vertical kidney grilles, Isle of Man Green metallic layers, and carbon roof weave highlights.',
    imageUrl: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#1E3A8A', '#111827', '#3B82F6', '#EF4444', '#F3F4F6'],
    paletteNames: ['M Motorsport Blue', 'Carbon Black', 'Electric Sky', 'M Red Accent', 'Alpine White'],
    featured: true,
    subCategory: 'BMW'
  },
  {
    id: 'pt-26',
    title: 'Audi R8 V10 Performance',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Cars',
    sizeCategory: 'Medium',
    widthCm: 90,
    heightCm: 70,
    price: 3360,
    story: 'The monolithic mid-engine supercar captured at full speed, emphasizing its unique carbon-blade intake doors, sharp laser headlights, and high-performance track agility.',
    imageUrl: 'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#374151', '#111827', '#EF4444', '#F9FAFB', '#6B7280'],
    paletteNames: ['Stealth Gray', 'Grille Black', 'Brake Red', 'Chrome Silver', 'Dark Graphite'],
    featured: true,
    subCategory: 'AUDI'
  },
  {
    id: 'pt-car-03',
    title: 'Toyota GR Supra JDM Spec',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Cars',
    sizeCategory: 'Large',
    widthCm: 120,
    heightCm: 85,
    price: 4710,
    story: 'Iconic 2JZ twin-turbo lineage meets sleek GR aeropackage. Rendered in high-octane Renaissance Red wash with aggressive tuner widebody stance and carbon ducktail spoiler.',
    imageUrl: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#B91C1C', '#111827', '#F59E0B', '#F3F4F6', '#4B5563'],
    paletteNames: ['Supra Crimson', 'Carbon Mesh', 'JDM Gold Accent', 'Pure Pearl White', 'Subframe Graphite'],
    featured: true,
    subCategory: 'Supra'
  },
  {
    id: 'pt-car-04',
    title: 'Nissan GT-R Nismo Godzilla',
    artistId: 'art-02',
    artistName: 'NOUREDDIN EL MOBARAKI',
    year: 2026,
    style: 'Cars',
    sizeCategory: 'Large',
    widthCm: 130,
    heightCm: 90,
    price: 4710,
    story: 'Legendary R35 Nismo AWD beast featuring exposed carbon-fiber bonnet louvers, twin-turbo roar, and iconic quad round rear taillight glow.',
    imageUrl: 'https://images.unsplash.com/photo-1611245141705-021e03a9484b?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#1F2937', '#DC2626', '#E5E7EB', '#111827', '#9CA3AF'],
    paletteNames: ['Nismo Stealth Gray', 'Red Striping', 'Chrome Lip', 'Midnight Carbon', 'Brake Caliper Silver'],
    featured: true,
    subCategory: 'Nissan'
  },
  {
    id: 'pt-car-05',
    title: 'Porsche 911 GT3 RS Stuttgart Spec',
    artistId: 'art-01',
    artistName: 'MESROUR SALAH EDDINE',
    year: 2026,
    style: 'Cars',
    sizeCategory: 'Large',
    widthCm: 120,
    heightCm: 90,
    price: 4710,
    story: 'Extreme track aerodynamic weapon featuring active DRS swan-neck rear wing, magnesium wheels, and high-revving 4.0L atmospheric flat-six roar.',
    imageUrl: 'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#D97706', '#111827', '#374151', '#F9FAFB', '#92400E'],
    paletteNames: ['Signal Yellow GT', 'Weissach Carbon', 'Graphite Wheel', 'Carrera White', 'PCCB Gold'],
    featured: true,
    subCategory: 'Porsche'
  },
  {
    id: 'pt-car-06',
    title: 'Custom Cyberpunk Hypercar Concept',
    artistId: 'art-02',
    artistName: 'NOUREDDIN EL MOBARAKI',
    year: 2026,
    style: 'Cars',
    sizeCategory: 'Large',
    widthCm: 120,
    heightCm: 80,
    price: 4710,
    story: 'Futuristic hypercar concept combining aggressive low-slung stance, active aero diffusers, and neon-infused carbon fiber bodywork.',
    imageUrl: 'https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?auto=format&fit=crop&q=80&w=1200',
    colorPalette: ['#111827', '#06B6D4', '#E11D48', '#F3F4F6', '#374151'],
    paletteNames: ['Midnight Obsidian', 'Neon Cyan Light', 'Crimson Tail', 'Starlight Silver', 'Chassis Slate'],
    featured: true,
    subCategory: 'another cars'
  }
];

/* ===========================================================================
 *  القائمة الموحّدة المعروضة للموقع بأكمله.
 *
 *  الترتيب مقصود: لوحات الورشة أولًا لأن HeroSection يقرأ
 *  PAINTINGS.filter(p => p.featured) ويتوقع لوحات الورشة في المقدمة.
 *
 *  حاجز أمان: أي تعارض في المعرّفات يكسر مفاتيح React ومفاتيح السلة
 *  (painting.id + frame.id) بصمت. لذلك نفحص في التطوير فقط.
 * ======================================================================== */
/*
 * كل اللوحات قبل الإخفاء. تُستخدم للتحقّق فقط، ولا تُصدَّر:
 * أي مستهلك يجب أن يرى النسخة المفلترة وحدها.
 */
const ALL_PAINTINGS: Painting[] = [...STUDIO_PAINTINGS, ...ART_PAINTINGS];

// يرمي خطأً واضحًا عند أول تحميل للوحدة إذا كان في قائمة الإخفاء معرّف خاطئ.
assertHiddenIdsResolve(ALL_PAINTINGS.map((p) => p.id));

/*
 * نقطة الخنق: كل ما يقرأ اللوحات في الموقع يقرأ هذا المصفوف —
 * المعرض، البحث، العدّادات، الستيكرات، الباكات، المحاكي، خريطة الموقع،
 * وكاروسيل الواجهة. الفلترة هنا مرة واحدة تعني اختفاءً كاملًا ومتّسقًا،
 * والترتيب يُغلق فوق الفراغ تلقائيًا لأن كل الشاشات ترقّم من المصفوف الناتج.
 */
export const PAINTINGS: Painting[] = ALL_PAINTINGS.filter((p) => !isHidden(p.id));

if ((import.meta as any).env?.DEV) {
  const seen = new Set<string>();
  const duplicates: string[] = [];

  for (const painting of PAINTINGS) {
    if (seen.has(painting.id)) duplicates.push(painting.id);
    seen.add(painting.id);
  }

  if (duplicates.length > 0) {
    console.error(
      `[PRISM] معرّفات لوحات مكررة (${duplicates.length}):`,
      duplicates,
    );
  }

  const outOfRange = PAINTINGS.filter((p) => p.price < 1000 || p.price > 8000);
  if (outOfRange.length > 0) {
    console.warn(
      `[PRISM] ${outOfRange.length} لوحة خارج نطاق مرشّح الميزانية [1000, 8000] ` +
      `— ستكون غير قابلة للوصول من المعرض.`,
      outOfRange.map((p) => `${p.id}: $${p.price}`),
    );
  }
}

export const FRAMING_OPTIONS: FramingOption[] = [
  {
    id: 'fr-01',
    name: 'Raw Galerie Oak',
    description: 'Sustainably sourced solid European White Oak with an ultra-matte protective finish. Emphasizes organic warmth, modern Scandinavian aesthetics, and delicate textures.',
    price: 290,
    borderHex: '#D2B48C', // Light wood tone
    materialWidthCm: 3.5
  },
  {
    id: 'fr-02',
    name: 'Matte Gallery Charcoal',
    description: 'Bespoke solid wood frame with an anodized-matte carbon black lacquer. Delivers a clean architectural border, perfect for focusing high-contrast and minimalist compositions.',
    price: 240,
    borderHex: '#1F1F1F', // Matte black
    materialWidthCm: 2.8
  },
  {
    id: 'fr-03',
    name: 'Gilded Heirloom Brass',
    description: 'Classic artisanal frame finished with hand-burnished 22k gold leaf over red bole clay. Lends an antique, historical depth and high-fashion contrast to modern abstracts.',
    price: 420,
    borderHex: '#C5A059', // Antique gold
    materialWidthCm: 4.0
  },
  {
    id: 'fr-00',
    name: 'Unframed Gallery Wrap',
    description: 'Traditional heavy-weight linen edges folded carefully over deep 4cm heavy timber stretchers. Clean museum presentation, letting the painted canvas edges bleed directly onto the wall.',
    price: 0,
    borderHex: 'transparent',
    materialWidthCm: 0
  }
];

export const ROOMS: RoomType[] = [
  {
    id: 'rm-01',
    name: 'Sofa Lounge, Paris',
    imageUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&q=80&w=1600',
    description: 'A Parisian apartment lounge with a neutral cream mohair sofa, marble accents, and a spacious wall under ambient studio lighting.',
    approxWidthM: 4.5,
    approxHeightM: 3.2,
    paintingDefaultXPercent: 50,
    paintingDefaultYPercent: 32,
    defaultScale: 1.15
  },
  {
    id: 'rm-02',
    name: 'Sleek Bureau, Munich',
    imageUrl: 'https://images.unsplash.com/photo-1531835551805-16d864c8d311?auto=format&fit=crop&q=80&w=1600',
    description: 'A modern design studio desk with warm wood textures, structural greenery, and elegant vertical space.',
    approxWidthM: 3.8,
    approxHeightM: 2.8,
    paintingDefaultXPercent: 50,
    paintingDefaultYPercent: 35,
    defaultScale: 1.0
  },
  {
    id: 'rm-03',
    name: 'Linen Chamber, Milan',
    imageUrl: 'https://images.unsplash.com/photo-1617806118233-18e1db207f62?auto=format&fit=crop&q=80&w=1600',
    description: 'A serene bedchamber styled with unbleached organic flax bedding and soft, filtered natural side light.',
    approxWidthM: 4.2,
    approxHeightM: 3.0,
    paintingDefaultXPercent: 50,
    paintingDefaultYPercent: 28,
    defaultScale: 1.1
  }
];
